## Numpy 

#### Creating numpy arrays from Python Lists

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
[3.14, 2, 4]

[3.14, 2, 4]

In [4]:
# numpy convert list number to the same data type
np.array([3.14,2,4])

array([3.14, 2.  , 4.  ])

In [5]:
np.array([1,2,3,4], dtype="float32")

array([1., 2., 3., 4.], dtype=float32)

In [6]:
a1 = np.array([1,2,3,4])
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1,2,3], [4,5,6]])
type(a2)

numpy.ndarray

#### Array Concatenation and Splitting

In [9]:
x = np.array([1,2,3])
y = np.array([3,2,1])

np.concatenate((x, y))

array([1, 2, 3, 3, 2, 1])

In [13]:
grid = np.array([[1,2,3], [4,5,6]])

np.concatenate((grid, grid))  #axis = 0 by default

np.concatenate((grid, grid), axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])