## Numpy 

#### Creating numpy arrays from Python Lists

In [1]:
import numpy as np

In [ ]:
np.array([1,2,3,4])

array([3.14, 2.  , 4.  ])

In [ ]:
[3.14, 2, 4]

In [ ]:
# numpy convert list number to the same data type
np.array([3.14,2,4])

array([3.14, 2.  , 4.  ])

In [7]:
np.array([1,2,3,4], dtype="float32")

array([1., 2., 3., 4.], dtype=float32)

In [8]:
a1 = np.array([1,2,3,4])
type(a1)

numpy.ndarray

In [10]:
a2 = np.array([[1,2,3], [4,5,6]])
type(a2)

numpy.ndarray